# Generated by Django 6.0.1 on 2026-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["position", "name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
